# AmyPatch Studio sketch — Juno + Reverb
# Generated from a PatchDoc. The code below is safe to edit; re-importing
# re-reads it and warns if it no longer matches the snapshot at the bottom.

import amy

amy.send(reset=8192)
amy.send(synth=1, num_voices=4, patch=10)
amy.send(reverb='0.4,0.85,0.5')

# amypatch:v1:16dc8b89300d47:eyJ2ZXJzaW9uIjoxLCJtZXRhIjp7ImlkIjoiMDAwMDAwMDAtMDAwMC00MDAwLTgwMDAtMDAwMDAwMDAwMDAwIiwibmFtZSI6Ikp1bm8gKyBSZXZlcmIiLCJ0YWdzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNi0wMS0wMVQwMDowMDowMC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjYtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIm9yaWdpbiI6Im1hbnVhbCJ9LCJtb2R1bGVzIjpbeyJpZCI6Imp1bm92b2ljZTEiLCJ0eXBlIjoiY29yZS5qdW5vdm9pY2UiLCJsYWJlbCI6Imp1bm92b2ljZTEiLCJwb3MiOnsieCI6MCwieSI6MH0sInBhcmFtcyI6eyJwYXRjaCI6MTAsInZvaWNlcyI6NH0sImFkdmFuY2VkIjpmYWxzZSwic3RhdGUiOnt9fSx7ImlkIjoicmV2ZXJiMSIsInR5cGUiOiJjb3JlLmZ4LnJldmVyYiIsImxhYmVsIjoicmV2ZXJiMSIsInBvcyI6eyJ4IjowLCJ5IjowfSwicGFyYW1zIjp7ImxldmVsIjowLjQsImxpdmVuZXNzIjowLjg1LCJkYW1waW5nIjowLjV9LCJhZHZhbmNlZCI6ZmFsc2UsInN0YXRlIjp7fX1dLCJjYWJsZXMiOltdLCJnbG9iYWxzIjp7ImVmZmVjdHMiOnt9LCJ0ZW1wbyI6MTA4LCJ2b2x1bWUiOjAuOH0sImlvIjp7Im1pZGlDaGFubmVsIjoxLCJjdkluIjpbXSwiY3ZPdXQiOltdfSwiYWxsb2NhdGlvbiI6eyJvc2NNYXAiOnt9LCJzeW50aE1hcCI6e319LCJleHRyYXMiOnsidW5tYXBwZWRXaXJlIjpbXSwidXNlckxvb3BDb2RlIjpudWxsfX0=
